#!/usr/bin/env python3
"""Generate the site icons from one source of truth.

``docs/favicon.svg``, ``docs/favicon.ico`` and ``docs/apple-touch-icon.png`` all
draw the same mark — a rounded brand-navy tile with a house — and used to be
maintained by hand. That drifted: the raster pair still carried the pre-Harbor
palette (a ``#1a2332`` tile and a ``#22c55e`` roof) long after the site moved to
Harbor, so the iOS home-screen icon no longer matched the site it opened.

Everything here derives from ``PALETTE`` below, which mirrors the CSS custom
properties in ``docs/style.css``. Change a colour there and re-run:

    python scripts/build_icons.py            # rewrite the three icon files
    python scripts/build_icons.py --check    # exit 1 if they are stale (CI)

The geometry is expressed once, in the 32-unit viewBox the SVG uses, and scaled
to whatever raster size is requested. The SVG markup is generated from those same
constants rather than kept as a literal, so the vector and bitmap marks cannot
disagree about where the roof sits. Rasters are drawn at 4x and downsampled so the
diagonal roof edges and the tile's rounded corners come out anti-aliased — Pillow's
polygon fill has no built-in AA.
"""

from __future__ import annotations

import argparse
import io
import pathlib
import sys

from PIL import Image, ImageDraw

_ROOT = pathlib.Path(__file__).resolve().parent.parent
DOCS = _ROOT / "docs"

# ── Palette (mirrors docs/style.css) ──────────────────────────────────────────
# --navy is the dark brand surface the nav, hero and footer already use, so the
# tile matches the top of the page the icon opens. The roof takes Harbor
# (--accent-on-dark), the accent reserved for brand marks sitting on that navy;
# --green is deliberately NOT used here because style.css scopes it to
# score-bar fills ("grades keep their own scale") — a green roof read as a
# grade signal, implying the label was rating itself. The house body is the
# warm paper the site's light theme is built on, which keeps the mark warm
# rather than clinical white.
PALETTE = {
    "tile":  "#13233d",   # --navy
    "roof":  "#4fb3d9",   # --accent-on-dark (Harbor)
    "body":  "#f6f4f0",   # --bg (warm paper)
    "door":  "#13233d",   # --navy, punched back out of the body
}

# ── Geometry, in the SVG's 32-unit box ────────────────────────────────────────
VIEW = 32.0
TILE_RADIUS = 7.0
ROOF = [(16, 6), (27, 15.5), (5, 15.5)]
BODY = (8.5, 15.5, 23.5, 26.0)      # x0, y0, x1, y1
BODY_RADIUS = 1.0
DOOR = (14.25, 19.5, 17.75, 26.0)
DOOR_RADIUS = 0.6

SUPERSAMPLE = 4


def _n(v: float) -> str:
    """Format a viewBox coordinate the way an SVG author would: 16, not 16.0."""
    return f"{v:g}"


def svg() -> str:
    """The vector mark, built from the same constants the rasters use.

    Written out rather than kept as a literal template so the SVG and the raster
    path cannot disagree about where the roof sits — one edit to ROOF/BODY/DOOR
    moves both.
    """
    (ax, ay), (bx, by), (cx, cy) = ROOF
    bx0, by0, bx1, by1 = BODY
    dx0, dy0, dx1, dy1 = DOOR
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {_n(VIEW)} {_n(VIEW)}"'
        f' width="{_n(VIEW)}" height="{_n(VIEW)}">\n'
        "  <!-- Housing Nutrition Label mark: brand-navy tile, Harbor roof, warm-paper house.\n"
        "       Generated by scripts/build_icons.py — edit PALETTE/geometry there, not here. -->\n"
        f'  <rect width="{_n(VIEW)}" height="{_n(VIEW)}" rx="{_n(TILE_RADIUS)}"'
        f' fill="{PALETTE["tile"]}"/>\n'
        "  <!-- Roof -->\n"
        f'  <path d="M{_n(ax)} {_n(ay)} L{_n(bx)} {_n(by)} L{_n(cx)} {_n(cy)} Z"'
        f' fill="{PALETTE["roof"]}"/>\n'
        "  <!-- House body -->\n"
        f'  <rect x="{_n(bx0)}" y="{_n(by0)}" width="{_n(bx1 - bx0)}"'
        f' height="{_n(by1 - by0)}" rx="{_n(BODY_RADIUS)}" fill="{PALETTE["body"]}"/>\n'
        "  <!-- Door -->\n"
        f'  <rect x="{_n(dx0)}" y="{_n(dy0)}" width="{_n(dx1 - dx0)}"'
        f' height="{_n(dy1 - dy0)}" rx="{_n(DOOR_RADIUS)}" fill="{PALETTE["door"]}"/>\n'
        "</svg>\n"
    )


def render(size: int, *, rounded: bool = True) -> Image.Image:
    """Draw the mark at ``size`` px square, anti-aliased via supersampling.

    ``rounded=False`` keeps the tile square — favicon.ico is shown at 16px in a
    browser tab where a 7/32 corner radius just erodes the silhouette.
    """
    s = size * SUPERSAMPLE
    k = s / VIEW                                  # viewBox units → supersampled px
    img = Image.new("RGBA", (s, s), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)

    if rounded:
        d.rounded_rectangle([0, 0, s - 1, s - 1], radius=TILE_RADIUS * k,
                            fill=PALETTE["tile"])
    else:
        d.rectangle([0, 0, s - 1, s - 1], fill=PALETTE["tile"])

    d.polygon([(x * k, y * k) for x, y in ROOF], fill=PALETTE["roof"])

    x0, y0, x1, y1 = (v * k for v in BODY)
    d.rounded_rectangle([x0, y0, x1, y1], radius=BODY_RADIUS * k, fill=PALETTE["body"])

    x0, y0, x1, y1 = (v * k for v in DOOR)
    d.rounded_rectangle([x0, y0, x1, y1], radius=DOOR_RADIUS * k, fill=PALETTE["door"])

    return img.resize((size, size), Image.LANCZOS)


def build() -> dict[pathlib.Path, bytes]:
    """Return {path: desired bytes} for every generated icon."""
    out: dict[pathlib.Path, bytes] = {}

    out[DOCS / "favicon.svg"] = svg().encode()

    # Apple touch icon: 180x180, opaque. iOS applies its own mask, and a
    # transparent margin would show the home-screen wallpaper through the
    # corners, so this one is flattened onto the tile colour.
    apple = Image.new("RGB", (180, 180), PALETTE["tile"])
    art = render(180)
    apple.paste(art, (0, 0), art)
    buf = io.BytesIO()
    apple.save(buf, format="PNG", optimize=True)
    out[DOCS / "apple-touch-icon.png"] = buf.getvalue()

    # Multi-size .ico so the tab, bookmark bar and desktop shortcut each get a
    # bitmap drawn for their size rather than one scaled badly.
    buf = io.BytesIO()
    base = render(64, rounded=False)
    base.save(buf, format="ICO", sizes=[(16, 16), (32, 32), (48, 48), (64, 64)])
    out[DOCS / "favicon.ico"] = buf.getvalue()

    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if any icon on disk differs from the generated one")
    args = ap.parse_args()

    stale = []
    for path, want in build().items():
        have = path.read_bytes() if path.exists() else None
        if have == want:
            continue
        stale.append(path.name)
        if not args.check:
            path.write_bytes(want)
            print(f"{path.relative_to(_ROOT)} updated.")

    if args.check:
        if stale:
            print("icons are out of date — run `python scripts/build_icons.py`: "
                  + ", ".join(stale), file=sys.stderr)
            return 1
        print("icons are in sync with the palette.")
    elif not stale:
        print("icons already up to date.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
